### ISSUE TITLE
execution stalls with blinking cursor

### ISSUE THREAD

**Issue by justinkreft** [amitsaha/gitbackup#19]
Following your article on Linux Journal and found this really useful. Learning Go at the moment.

Problem I had is on Ubuntu Bionic
`gitbackup-v0.3-linux-amd64 -service gitlab -backupdir ~/gitbackup/`

Executes successfully and doesn't have an auth error, but just sits at terminal with blinking cursor.

**Comment by amitsaha** [comment]
Hm, a `-verbose` flag would be useful. Did you take a look at the `~/gitbackup` directory to see if it's actually doing anything useful? If  you have already, and it is actually not doing anything - I would have to look.

**Comment by liljenstolpe** [comment]
The reason this is "stalling" is the default is visibility 'internal' which means that gitbackup is enumerating ALL projects/repos that any gitlab user can see if logged in (so all repos owned by any gitlab user that has been marked as internal).  It takes A LONG TIME (not as long as public, however).  It will start, and then you will have LOTS of repos being backed up (hope you have disk).

See #22 for further details.

**Comment by amitsaha** [comment]
Thanks @liljenstolpe - i think that's it. @justinkreft the next release will have a fix for this.

**Comment by amitsaha** [comment]
Release 0.4 introduces a new option for project membership. https://github.com/amitsaha/gitbackup/releases/tag/0.4
