### ISSUE TITLE
GitHub: Can't backup private github org repos

### ISSUE THREAD

**Issue by liljenstolpe** [amitsaha/gitbackup#21]
Greetings,

I have access to private repos on a few github orgs, and they are "found" by gitbackup, but when it attempts to clone them it fails with "repo not found"  It obviously found the repo, otherwise it wouldn't have known to try and clone it.  

Private repos under my user work.

Christopher

**Comment by amitsaha** [comment]
Hi @liljenstolpe - any chance it could be a case of you not granting the necessary scopes to the oauth token you are using?

**Comment by amitsaha** [comment]
hi @liljenstolpe - if you get a chance, please let know if the new release https://github.com/amitsaha/gitbackup/releases/tag/0.5 fixes the issue?
