### ISSUE TITLE
visibility in gitlab is a bit too broad

### ISSUE THREAD

**Issue by liljenstolpe** [amitsaha/gitbackup#22]
Greetings,

In gitlab's API, visibility toggles what repos you can see across all of gitlab, not just your projects.  So, a public visibility will iterate (and backup) ALL public projects in gitlab, probably not what you want.  internal will backup all projects available to anyone that is logged into gitlab, etc.

Gitlab has the same construct as github, with member and owner.  Could we get the same setting for gitlab as github (i.e. gitlab.repoType [all, owner, membership]?

**Comment by amitsaha** [comment]
Release 0.4 introduces a new option for project membership. https://github.com/amitsaha/gitbackup/releases/tag/0.4

Thanks for reporting this issue and suggesting the solution @liljenstolpe
