### ISSUE TITLE
How does the backup work?

### ISSUE THREAD

**Issue by lucaszanella** [amitsaha/gitbackup#29]
It isn't clean in the readme how the backup works. Is it a mirror? If I mess with the official git repository it will mess in the backup one? Or is it just a tree snapshot?

ps: why do I need to provide credentials for public repositories?

**Comment by amitsaha** [comment]
Hi @lucaszanella - backup right now is a `git clone` for the first backup and then `git pull` on subsequent backups.

Currently the token is used to access the GitHub/GitLab API. Hence it is needed for public repositories as well.

**Comment by amitsaha** [comment]
Added as a FAQ entry in https://github.com/amitsaha/gitbackup/pull/58/files
