### ISSUE TITLE
Feature Request: Full Backup

### ISSUE THREAD

**Issue by jvmatl** [amitsaha/gitbackup#31]
Hi!

Thanks for this tool - saved me a ton of work!

The 'backup' created by this program uses a normal `git clone` to a working git repo. This is fine for some use cases but it does not, for example, backup remote branches. (e.g. if I push to a non-default branch, it shows up in my gitlab, but the branch does not get pulled over to the backup. So if I later lose my gitlab and have to restore, I have no (easy) way to access my work that was on that branch). 

To get a more complete backup, I forked the package (see https://github.com/jvmatl/gitbackup) to use `git clone --mirror` for the backups and `git remote update` for the updates. This gives me a more complete backup, but with the downside that it creates a 'bare' git repo, and so you have to clone from the mirror to another 'working' repo to see the files. (The [changes are pretty trivial](https://github.com/jvmatl/gitbackup/commit/f072660ccf92ad8ef25a41b281482382be4471ee#diff-2489c938a3abbd8b8ac7d9d34402a8e4) if you want to integrate them yourself) 

Eventually I intend to make this 'full' backup a CLI option (since the changed behavior would probably freak out your existing users when they find no working tree in their backup) and offer a PR, but I'm in a hurry, so I just forked the default behavior.

**Comment by amitsaha** [comment]
Hi @jvmatl thanks- i am glad it is proving to useful. 

Excellent point regarding the incompleteness of the backup. I have an in-progress branch (https://github.com/amitsaha/gitbackup/tree/isw) where I wanted to implemented a new feature which would allow you to sync to gitlab and vice-versa. I ran into the same issue as you did above and realized as much. Do you have time to invest into completing it? If so, i can share some more details around the current state.

**Comment by jvmatl** [comment]
Hi,

I'm currently in crunch time at work, so I don't have a lot of time to spare -- thats why I had to do the hacky thing in the first place :) -- but thank you for the invitation.
