### ISSUE TITLE
`-gitlab.projectMembershipType all` doesn't seem to include "maintainer"

### ISSUE THREAD

**Issue by gdetrez** [amitsaha/gitbackup#32]
When running `gitbackup` without specifying `-gitlab.projectMembershipType`, it didn't backup the gitlab repository where I have the "maintainer" access level.  Using `gitbackup -gitlab.projectMembershipType maintainer` worked but included all the repositories, even those where I have "owner" access (which is what I wanted so it's fine but it's not what one might expect).

Edit: it seems that there's nothing special with the string "maintainer": `gitbackup` will backup all the repository if I use any arbitrary string, e.g. `-gitlab.projectMembershipType foo`.

**Comment by amitsaha** [comment]
@gdetrez gitlab only has the concept of an "owner" or a "member" of a repo (AFAI can see). `gitbackup` should ideally error out when one of "owner", "member", "all" is not specified. "all" which is the default results in fetching all the projects where you are either a "owner" or a "member".

PR for erroring out: https://github.com/amitsaha/gitbackup/pull/33

**Comment by amitsaha** [comment]
On further investigation, I can see there is a concept of a minimum access level: https://docs.gitlab.com/ee/api/projects.html#list-user-projects which then points to https://docs.gitlab.com/ce/api/access_requests.html#valid-access-levels 

So, i think that's something we can look into.
