### ISSUE TITLE
can't backup anything

### ISSUE THREAD

**Issue by hadifarnoud** [amitsaha/gitbackup#37]
running `GITLAB_TOKEN=********* ./gitbackup-0.5-darwin-amd64 -service gitlab` only reports `2020/10/11 01:26:45 Backing up 0 repositories now..`

I have more than 150 repo in this account.

**Comment by amitsaha** [comment]
Interesting. Are your projects all public, internal or a mix?

**Comment by hadifarnoud** [comment]
it's a mix but mostly private

**Comment by amitsaha** [comment]
Do you want to try running with: `-gitlab.projectVisibility private`?

**Comment by hadifarnoud** [comment]
it worked thanks. It's weird I had two public repo but didn't back them up

**Comment by amitsaha** [comment]
Great, Can you please link me to the public repos?

**Comment by hadifarnoud** [comment]
https://gitlab.com/pakat/woocommerce-plugin

**Comment by hadifarnoud** [comment]
I checked the backup folder, only private repos are backed up

**Comment by amitsaha** [comment]
Hi @hadifarnoud are you able to try this with the latest release? And can you please post the exact commands you ran, and the behavior, that will be great.

**Comment by amitsaha** [comment]
Closing this due to lack of response.
