### ISSUE TITLE
GitLab: Allow to clone starred repos in GitLab

### ISSUE THREAD

**Issue by trenta3** [amitsaha/gitbackup#59]
Currently there is a great functionality of backing up all starred repositories on GitHub, but such functionality is not paralled in GitLab.
It would be great to add.

**Comment by amitsaha** [comment]
Released: https://github.com/amitsaha/gitbackup/releases/tag/v0.8.0

Thanks for filing the issue. Hope you will get to try it out.

**Comment by trenta3** [comment]
Thank you very much! I tested it locally and it works!
