### ISSUE TITLE
Intermitent errors while using migration api backup on github 

### ISSUE THREAD

**Issue by DiegoSpinola** [amitsaha/gitbackup#62]
First and foremost , this is a great tool and I have been using it to automate my repo backups (Thanks!)

I noticed this in the last few weeks( it appears to be happening intermittently) :

```
2021/10/24 06:05:02 <Redacted>/backups/github.com doesn't exist, creating it
2021/10/24 06:05:02 Creating a user migration for 1 repos
2021/10/24 06:05:03 Waiting for migration state to be exported: 0xc00018d6a0
2021/10/24 06:06:03 Downloading file to: <Redacted>/backups/github.com/user-migration-720156.tar.gz
2021/10/24 06:06:08 Creating a org migration (<Redacted>) for 106 repos
2021/10/24 06:06:18 {
"message": "Server Error"
}
2021/10/24 06:06:18 Error creating migration: POST https://api.github.com/orgs/<Redacted>/migrations: 502 Server Error []
Result is: 1
backup failed...
```

Since then modified my script so as to check the result of gitbackup and to retry a few times with exponential backoff... it seems to do the trick I evenctually get a migration backup to "stick" every 5 tries...

My guesses:

- anecdotally I think it coincides with my organization having passed 100 repos which , not knowing the underlying API used, would lead me to believe it might be because of some "paging" issue with the migration API maybe?
- It may be due to some infrastructure weirdness by github's API while serving my particlar location (south america....I'm thinking about trying these requests from a different server elsewhere in the globe, it wouldn't be the first time I see such things)

either way I think it is relevant enough to post here as an FYI

DS

**Comment by DiegoSpinola** [comment]
Hi there @amitsaha , sorry for the delayed reply I was out of office for a while I think the back off + retry mechanism in the application would be a great addition! 

I reviewed my logs and tried to run my backup on multiple routes/VMs located on different continents, they all present this intermittent error at some point... I couldn't extract any pattern out of it though (no location correlation)

**Comment by amitsaha** [comment]
I will keep this open, till the above attempted fix resolves the issue.

**Comment by amitsaha** [comment]
The above change definitely has helped as far my own backups go. I am refactoring the retry logic now in https://github.com/amitsaha/gitbackup/pull/64 and also adding tests.

**Comment by amitsaha** [comment]
The retry logic seems to be working. The change is included in https://github.com/amitsaha/gitbackup/releases/tag/v0.7.0
