### ISSUE TITLE
GithubAction: Permission denied

### ISSUE THREAD

**Issue by saltbo** [amitsaha/gitbackup#87]
./gitbackup -service github -ignore-fork -ignore-private -github.repoType owner -bare

git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

https://github.com/saltbo/gitweb/actions/runs/3427107635/jobs/5709704086

**Comment by amitsaha** [comment]
Documented at https://github.com/amitsaha/gitbackup#security-and-credentials
