### ISSUE TITLE
App still using SSH with -use-https-clone

### ISSUE THREAD

**Issue by pbougie** [amitsaha/gitbackup#93]
When backing up my GitHub repos using:

```
GITHUB_TOKEN=<token> gitbackup -service github -use-https-clone
```

About half way through the repos, I am prompted for my SSH key. Most users might not notice this if using a traditional SSH config but my SSH keys are hosted in 1Password and need to be authenticated using Touch ID. This makes it impossible to automate. I understood that using `-use-https-clone` would not require SSH and would perform the backup using the provided _Personal Access Token_ over HTTPS. Is SSH being used for something else?

**Comment by amitsaha** [comment]
Hi @pbougie your expectation is right here.

Can you tell me a little bit about your repositories? 
1. I imagine they are private repositories which is why you are using `https-clone`? 
2. They aren't a specific org's private repositories and you have confirmed you can access them?

**Comment by pbougie** [comment]
@amitsaha Mix of personal and organization repos, both public and private. Using `-use-https-clone` because I want to automate with a _Personal Access Token_ and not use SSH because I have to manually authenticate with Touch ID. I've used another backup app (https://github.com/qvl/ghbackup) in the past and it was capable of backing up everything with only a _Personal Access Token_ (with only repo scope).

**Comment by amitsaha** [comment]
@pbougie i finally got a chance to verify that i can reproduce the issue, and the answer is I can't. I have a mix of private and public repositories, in organizations which I am a member of as well as my own.

Are you using a GitHub "classic token" and have ensured that you have created with the mentioned scopes?  https://github.com/amitsaha/gitbackup#github

**Comment by pbougie** [comment]
@amitsaha I am using a GitHub classic token with the specified scopes. I cannot however see logs as you specified. Is there a verbosity switch? Where are the logs located? I have installed `gitbackup` using Homebrew. I'm running version `0.9.0`.

**Comment by amitsaha** [comment]
@pbougie that's strange. I just confirmed my findings in https://github.com/amitsaha/gitbackup/issues/93#issuecomment-1690636819 using 0.9.0 from homebrew

All logs are emitted to standard output and error - so they should be visible in your terminal.

**Comment by amitsaha** [comment]
@pbougie Is that all you see or are there further logs after that?

**Comment by pbougie** [comment]
@amitsaha The remaining lines are a repeat of line 2 for all the other repos. Nothing more. Are you using an undocumented CLI argument for more verbose logs?

**Comment by amitsaha** [comment]
@pbougie ah i missed the "updating message", it appears that you have already run gitbackup before, so it is not trying to do a fresh clone, but doing an update.

Can you please delete your `~./.gitbackup` directory (the default location for backup) and run `gitbackup` once more? that will give you the clone URLs.

Alternatively, if bandwidth is an issue, you can navigate to the backup directory and see what the clone URLs are in the `.git/config` directory for the repositories (`origin` url)? If you have noted that you are only getting asked for the SSH key for a certain specific repository, that origin URL will be interesting to look at as well.

**Comment by pbougie** [comment]
@amitsaha Ok that worked! I must have initially done the backup without `-use-https-clone`. My backup is 2+ GB so I hadn't deleted it. There should be a warning if `-use-https-clone` is used but the backup is being done with another method. Or it should automatically switch the method to `https` if that's possible. I would perhaps leave the more verbose logging when updating also.

**Comment by amitsaha** [comment]
Great to hear it worked.

And agree with your suggestions, could you please create them as new issues?

**Comment by pbougie** [comment]
@amitsaha Two new issues created. Closing this one.

**Comment by amitsaha** [comment]
Thank you.
